package com.mall.mbg.mapper;

import com.mall.mbg.model.CmsHelp;
import com.mall.mbg.model.CmsHelpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsHelpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    long countByExample(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int deleteByExample(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int insert(CmsHelp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int insertSelective(CmsHelp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    List<CmsHelp> selectByExampleWithBLOBs(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    List<CmsHelp> selectByExample(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    CmsHelp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByExampleSelective(@Param("row") CmsHelp row, @Param("example") CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") CmsHelp row, @Param("example") CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByExample(@Param("row") CmsHelp row, @Param("example") CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByPrimaryKeySelective(CmsHelp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(CmsHelp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByPrimaryKey(CmsHelp row);
}