package com.mall.mbg.mapper;

import com.mall.mbg.model.CmsMemberReport;
import com.mall.mbg.model.CmsMemberReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsMemberReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_member_report
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    long countByExample(CmsMemberReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_member_report
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int deleteByExample(CmsMemberReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_member_report
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int insert(CmsMemberReport row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_member_report
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int insertSelective(CmsMemberReport row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_member_report
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    List<CmsMemberReport> selectByExample(CmsMemberReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_member_report
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByExampleSelective(@Param("row") CmsMemberReport row, @Param("example") CmsMemberReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_member_report
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByExample(@Param("row") CmsMemberReport row, @Param("example") CmsMemberReportExample example);
}