package com.mall.mbg.mapper;

import com.mall.mbg.model.CmsSubject;
import com.mall.mbg.model.CmsSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    long countByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int deleteByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int insert(CmsSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int insertSelective(CmsSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    List<CmsSubject> selectByExampleWithBLOBs(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    List<CmsSubject> selectByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    CmsSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByExampleSelective(@Param("row") CmsSubject row, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") CmsSubject row, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByExample(@Param("row") CmsSubject row, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByPrimaryKeySelective(CmsSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(CmsSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByPrimaryKey(CmsSubject row);
}