package com.mall.mbg.mapper;

import com.mall.mbg.model.CmsTopic;
import com.mall.mbg.model.CmsTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    long countByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int deleteByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int insert(CmsTopic row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int insertSelective(CmsTopic row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    List<CmsTopic> selectByExampleWithBLOBs(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    List<CmsTopic> selectByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    CmsTopic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByExampleSelective(@Param("row") CmsTopic row, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") CmsTopic row, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByExample(@Param("row") CmsTopic row, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByPrimaryKeySelective(CmsTopic row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(CmsTopic row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByPrimaryKey(CmsTopic row);
}