package com.mall.mbg.mapper;

import com.mall.mbg.model.PmsCommentReplay;
import com.mall.mbg.model.PmsCommentReplayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsCommentReplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    long countByExample(PmsCommentReplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int deleteByExample(PmsCommentReplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int insert(PmsCommentReplay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int insertSelective(PmsCommentReplay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    List<PmsCommentReplay> selectByExample(PmsCommentReplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    PmsCommentReplay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") PmsCommentReplay row, @Param("example") PmsCommentReplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int updateByExample(@Param("row") PmsCommentReplay row, @Param("example") PmsCommentReplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int updateByPrimaryKeySelective(PmsCommentReplay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int updateByPrimaryKey(PmsCommentReplay row);
}