package com.mall.mbg.mapper;

import com.mall.mbg.model.PmsFreightTemplate;
import com.mall.mbg.model.PmsFreightTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsFreightTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    long countByExample(PmsFreightTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int deleteByExample(PmsFreightTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int insert(PmsFreightTemplate row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int insertSelective(PmsFreightTemplate row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    List<PmsFreightTemplate> selectByExample(PmsFreightTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    PmsFreightTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByExampleSelective(@Param("row") PmsFreightTemplate row, @Param("example") PmsFreightTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByExample(@Param("row") PmsFreightTemplate row, @Param("example") PmsFreightTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByPrimaryKeySelective(PmsFreightTemplate row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByPrimaryKey(PmsFreightTemplate row);
}