package com.mall.mbg.mapper;

import com.mall.mbg.model.PmsProductFullReduction;
import com.mall.mbg.model.PmsProductFullReductionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductFullReductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    long countByExample(PmsProductFullReductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int deleteByExample(PmsProductFullReductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int insert(PmsProductFullReduction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int insertSelective(PmsProductFullReduction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    List<PmsProductFullReduction> selectByExample(PmsProductFullReductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    PmsProductFullReduction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByExampleSelective(@Param("row") PmsProductFullReduction row, @Param("example") PmsProductFullReductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByExample(@Param("row") PmsProductFullReduction row, @Param("example") PmsProductFullReductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByPrimaryKeySelective(PmsProductFullReduction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_full_reduction
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByPrimaryKey(PmsProductFullReduction row);
}