package com.mall.mbg.mapper;

import com.mall.mbg.model.PmsProductLadder;
import com.mall.mbg.model.PmsProductLadderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductLadderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    long countByExample(PmsProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    int deleteByExample(PmsProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    int insert(PmsProductLadder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    int insertSelective(PmsProductLadder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    List<PmsProductLadder> selectByExample(PmsProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    PmsProductLadder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    int updateByExampleSelective(@Param("row") PmsProductLadder row, @Param("example") PmsProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    int updateByExample(@Param("row") PmsProductLadder row, @Param("example") PmsProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    int updateByPrimaryKeySelective(PmsProductLadder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    int updateByPrimaryKey(PmsProductLadder row);
}