package com.mall.mbg.mapper;

import com.mall.mbg.model.PmsProductAlbumRelation;
import com.mall.mbg.model.PmsProductAlbumRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductAlbumRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    long countByExample(PmsProductAlbumRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int deleteByExample(PmsProductAlbumRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int insert(PmsProductAlbumRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int insertSelective(PmsProductAlbumRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    List<PmsProductAlbumRelation> selectByExample(PmsProductAlbumRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    PmsProductAlbumRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") PmsProductAlbumRelation row, @Param("example") PmsProductAlbumRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int updateByExample(@Param("row") PmsProductAlbumRelation row, @Param("example") PmsProductAlbumRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int updateByPrimaryKeySelective(PmsProductAlbumRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    int updateByPrimaryKey(PmsProductAlbumRelation row);
}