package com.mall.mbg.mapper;

import com.mall.mbg.model.PmsSkuStock;
import com.mall.mbg.model.PmsSkuStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsSkuStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    long countByExample(PmsSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int deleteByExample(PmsSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int insert(PmsSkuStock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int insertSelective(PmsSkuStock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    List<PmsSkuStock> selectByExample(PmsSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    PmsSkuStock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByExampleSelective(@Param("row") PmsSkuStock row, @Param("example") PmsSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByExample(@Param("row") PmsSkuStock row, @Param("example") PmsSkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByPrimaryKeySelective(PmsSkuStock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByPrimaryKey(PmsSkuStock row);
}