package com.mall.mbg.mapper;

import com.mall.mbg.model.SmsCouponProductRelation;
import com.mall.mbg.model.SmsCouponProductRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsCouponProductRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    long countByExample(SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int deleteByExample(SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int insert(SmsCouponProductRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int insertSelective(SmsCouponProductRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    List<SmsCouponProductRelation> selectByExample(SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    SmsCouponProductRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int updateByExampleSelective(@Param("row") SmsCouponProductRelation row, @Param("example") SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int updateByExample(@Param("row") SmsCouponProductRelation row, @Param("example") SmsCouponProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int updateByPrimaryKeySelective(SmsCouponProductRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int updateByPrimaryKey(SmsCouponProductRelation row);
}