package com.mall.mbg.mapper;

import com.mall.mbg.model.SmsFlashPromotionLog;
import com.mall.mbg.model.SmsFlashPromotionLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsFlashPromotionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    long countByExample(SmsFlashPromotionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int deleteByExample(SmsFlashPromotionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int insert(SmsFlashPromotionLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int insertSelective(SmsFlashPromotionLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    List<SmsFlashPromotionLog> selectByExample(SmsFlashPromotionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    SmsFlashPromotionLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByExampleSelective(@Param("row") SmsFlashPromotionLog row, @Param("example") SmsFlashPromotionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByExample(@Param("row") SmsFlashPromotionLog row, @Param("example") SmsFlashPromotionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByPrimaryKeySelective(SmsFlashPromotionLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    int updateByPrimaryKey(SmsFlashPromotionLog row);
}