package com.mall.mbg.mapper;

import com.mall.mbg.model.SmsFlashStockFlow;
import com.mall.mbg.model.SmsFlashStockFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsFlashStockFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    long countByExample(SmsFlashStockFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int deleteByExample(SmsFlashStockFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int insert(SmsFlashStockFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int insertSelective(SmsFlashStockFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    List<SmsFlashStockFlow> selectByExample(SmsFlashStockFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    SmsFlashStockFlow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByExampleSelective(@Param("row") SmsFlashStockFlow row, @Param("example") SmsFlashStockFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByExample(@Param("row") SmsFlashStockFlow row, @Param("example") SmsFlashStockFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByPrimaryKeySelective(SmsFlashStockFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_stock_flow
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByPrimaryKey(SmsFlashStockFlow row);
}