package com.mall.mbg.mapper;

import com.mall.mbg.model.SmsFlashBehavior;
import com.mall.mbg.model.SmsFlashBehaviorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsFlashBehaviorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    long countByExample(SmsFlashBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int deleteByExample(SmsFlashBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int insert(SmsFlashBehavior row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int insertSelective(SmsFlashBehavior row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    List<SmsFlashBehavior> selectByExample(SmsFlashBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    SmsFlashBehavior selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByExampleSelective(@Param("row") SmsFlashBehavior row, @Param("example") SmsFlashBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByExample(@Param("row") SmsFlashBehavior row, @Param("example") SmsFlashBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByPrimaryKeySelective(SmsFlashBehavior row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    int updateByPrimaryKey(SmsFlashBehavior row);
}