package com.mall.mbg.mapper;

import com.mall.mbg.model.SmsHomeAdvertise;
import com.mall.mbg.model.SmsHomeAdvertiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsHomeAdvertiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    long countByExample(SmsHomeAdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int deleteByExample(SmsHomeAdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int insert(SmsHomeAdvertise row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int insertSelective(SmsHomeAdvertise row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    List<SmsHomeAdvertise> selectByExample(SmsHomeAdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    SmsHomeAdvertise selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByExampleSelective(@Param("row") SmsHomeAdvertise row, @Param("example") SmsHomeAdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByExample(@Param("row") SmsHomeAdvertise row, @Param("example") SmsHomeAdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByPrimaryKeySelective(SmsHomeAdvertise row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_advertise
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByPrimaryKey(SmsHomeAdvertise row);
}