package com.mall.mbg.mapper;

import com.mall.mbg.model.SmsHomeNewProduct;
import com.mall.mbg.model.SmsHomeNewProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsHomeNewProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    long countByExample(SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    int deleteByExample(SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    int insert(SmsHomeNewProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    int insertSelective(SmsHomeNewProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    List<SmsHomeNewProduct> selectByExample(SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    SmsHomeNewProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    int updateByExampleSelective(@Param("row") SmsHomeNewProduct row, @Param("example") SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    int updateByExample(@Param("row") SmsHomeNewProduct row, @Param("example") SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    int updateByPrimaryKeySelective(SmsHomeNewProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Thu Jun 19 11:50:17 CST 2025
     */
    int updateByPrimaryKey(SmsHomeNewProduct row);
}