package com.mall.mbg.mapper;

import com.mall.mbg.model.SmsHomeBrand;
import com.mall.mbg.model.SmsHomeBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsHomeBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    long countByExample(SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int deleteByExample(SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int insert(SmsHomeBrand row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int insertSelective(SmsHomeBrand row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    List<SmsHomeBrand> selectByExample(SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    SmsHomeBrand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByExampleSelective(@Param("row") SmsHomeBrand row, @Param("example") SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByExample(@Param("row") SmsHomeBrand row, @Param("example") SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByPrimaryKeySelective(SmsHomeBrand row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByPrimaryKey(SmsHomeBrand row);
}