package com.mall.mbg.mapper;

import com.mall.mbg.model.UmsMemberMemberTagRelation;
import com.mall.mbg.model.UmsMemberMemberTagRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberMemberTagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    long countByExample(UmsMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int deleteByExample(UmsMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int insert(UmsMemberMemberTagRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int insertSelective(UmsMemberMemberTagRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    List<UmsMemberMemberTagRelation> selectByExample(UmsMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    UmsMemberMemberTagRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int updateByExampleSelective(@Param("row") UmsMemberMemberTagRelation row, @Param("example") UmsMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int updateByExample(@Param("row") UmsMemberMemberTagRelation row, @Param("example") UmsMemberMemberTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int updateByPrimaryKeySelective(UmsMemberMemberTagRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    int updateByPrimaryKey(UmsMemberMemberTagRelation row);
}