package com.mall.mbg.mapper;

import com.mall.mbg.model.UmsMemberTask;
import com.mall.mbg.model.UmsMemberTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    long countByExample(UmsMemberTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int deleteByExample(UmsMemberTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int insert(UmsMemberTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int insertSelective(UmsMemberTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    List<UmsMemberTask> selectByExample(UmsMemberTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    UmsMemberTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByExampleSelective(@Param("row") UmsMemberTask row, @Param("example") UmsMemberTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByExample(@Param("row") UmsMemberTask row, @Param("example") UmsMemberTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByPrimaryKeySelective(UmsMemberTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Wed Jun 18 16:38:24 CST 2025
     */
    int updateByPrimaryKey(UmsMemberTask row);
}