package com.mall.mbg.mapper;

import com.mall.mbg.model.UmsMemberLevel;
import com.mall.mbg.model.UmsMemberLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    long countByExample(UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int deleteByExample(UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int insert(UmsMemberLevel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int insertSelective(UmsMemberLevel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    List<UmsMemberLevel> selectByExample(UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    UmsMemberLevel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByExampleSelective(@Param("row") UmsMemberLevel row, @Param("example") UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByExample(@Param("row") UmsMemberLevel row, @Param("example") UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByPrimaryKeySelective(UmsMemberLevel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    int updateByPrimaryKey(UmsMemberLevel row);
}