package com.mall.mbg.mapper;

import com.mall.mbg.model.UmsMemberTag;
import com.mall.mbg.model.UmsMemberTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    long countByExample(UmsMemberTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    int deleteByExample(UmsMemberTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    int insert(UmsMemberTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    int insertSelective(UmsMemberTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    List<UmsMemberTag> selectByExample(UmsMemberTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    UmsMemberTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    int updateByExampleSelective(@Param("row") UmsMemberTag row, @Param("example") UmsMemberTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    int updateByExample(@Param("row") UmsMemberTag row, @Param("example") UmsMemberTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    int updateByPrimaryKeySelective(UmsMemberTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Thu Jun 19 11:50:16 CST 2025
     */
    int updateByPrimaryKey(UmsMemberTag row);
}