package com.mall.mbg.mapper;

import com.mall.mbg.model.UmsMemberRuleSetting;
import com.mall.mbg.model.UmsMemberRuleSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberRuleSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    long countByExample(UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int deleteByExample(UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int insert(UmsMemberRuleSetting row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int insertSelective(UmsMemberRuleSetting row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    List<UmsMemberRuleSetting> selectByExample(UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    UmsMemberRuleSetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByExampleSelective(@Param("row") UmsMemberRuleSetting row, @Param("example") UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByExample(@Param("row") UmsMemberRuleSetting row, @Param("example") UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByPrimaryKeySelective(UmsMemberRuleSetting row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Jun 18 16:38:25 CST 2025
     */
    int updateByPrimaryKey(UmsMemberRuleSetting row);
}