server:
  port: 8001

spring:
  application:
    name:
      portal
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    user: root
    password: 12345678
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

    data:
      mongodb:
        host: localhost
        port: 27017
        database: portal
        auto-index-creation: true # 自动创建索引

    redis:
      host: localhost # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      timeout: 300ms # 连接超时时间（毫秒）

    rabbitmq:
      port: 5672
      virtual-host: /mall
      username: admin
      password: 13232112651
      host: 159.75.68.114
      publisher-confirms: true # 发布者模式 消息发送到交换机(找到交换机和路由) 服务器返回 ack/nack
      publisher-returns: true # 发布者返回模式 消息到达交换机未找到队列 服务器将消息返回
      listener:
        direct:
          acknowledge-mode: manual # 监听direct 消息手动确认
        simple:
          acknowledge-mode=manual: manual
          concurrency: 1 #指定最小的消费者数量
          max-concurrency: 1 #指定最大的消费者数量
          retry:
            enabled: true #是否支持重试

logging:
  level:
    root: info
    com.mall: debug

logstash:
  host: localhost
  enableInnerLog: false

cache:
  allow:
    product: true

alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: your appId
  alipayPublicKey: your alipayPublicKey
  appPrivateKey: your appPrivateKey
  returnUrl: http://localhost:8060/#/pages/money/paySuccess
  notifyUrl: