package com.mall.mbg.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   商品评价表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_comment
 */
public class PmsComment implements Serializable {
    private Long id;

    private Long productId;

    private Long memberId;

    private String memberNickName;

    private String memberIcon;

    private String productName;

    private Integer star;

    private String content;

    private String pics;

    private Integer replayCount;

    private Boolean showStatus;

    private Date createTime;

    private String productAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_comment
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.id
     *
     * @return the value of pms_comment.id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.id
     *
     * @param id the value for pms_comment.id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.product_id
     *
     * @return the value of pms_comment.product_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.product_id
     *
     * @param productId the value for pms_comment.product_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.member_id
     *
     * @return the value of pms_comment.member_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.member_id
     *
     * @param memberId the value for pms_comment.member_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.member_nick_name
     *
     * @return the value of pms_comment.member_nick_name
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getMemberNickName() {
        return memberNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.member_nick_name
     *
     * @param memberNickName the value for pms_comment.member_nick_name
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setMemberNickName(String memberNickName) {
        this.memberNickName = memberNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.member_icon
     *
     * @return the value of pms_comment.member_icon
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getMemberIcon() {
        return memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.member_icon
     *
     * @param memberIcon the value for pms_comment.member_icon
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setMemberIcon(String memberIcon) {
        this.memberIcon = memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.product_name
     *
     * @return the value of pms_comment.product_name
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.product_name
     *
     * @param productName the value for pms_comment.product_name
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.star
     *
     * @return the value of pms_comment.star
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.star
     *
     * @param star the value for pms_comment.star
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.content
     *
     * @return the value of pms_comment.content
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.content
     *
     * @param content the value for pms_comment.content
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.pics
     *
     * @return the value of pms_comment.pics
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.pics
     *
     * @param pics the value for pms_comment.pics
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setPics(String pics) {
        this.pics = pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.replay_count
     *
     * @return the value of pms_comment.replay_count
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Integer getReplayCount() {
        return replayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.replay_count
     *
     * @param replayCount the value for pms_comment.replay_count
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setReplayCount(Integer replayCount) {
        this.replayCount = replayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.show_status
     *
     * @return the value of pms_comment.show_status
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Boolean getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.show_status
     *
     * @param showStatus the value for pms_comment.show_status
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setShowStatus(Boolean showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.create_time
     *
     * @return the value of pms_comment.create_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.create_time
     *
     * @param createTime the value for pms_comment.create_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment.product_attribute
     *
     * @return the value of pms_comment.product_attribute
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getProductAttribute() {
        return productAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment.product_attribute
     *
     * @param productAttribute the value for pms_comment.product_attribute
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setProductAttribute(String productAttribute) {
        this.productAttribute = productAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_comment
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", memberId=").append(memberId);
        sb.append(", memberNickName=").append(memberNickName);
        sb.append(", memberIcon=").append(memberIcon);
        sb.append(", productName=").append(productName);
        sb.append(", star=").append(star);
        sb.append(", content=").append(content);
        sb.append(", pics=").append(pics);
        sb.append(", replayCount=").append(replayCount);
        sb.append(", showStatus=").append(showStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", productAttribute=").append(productAttribute);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}