package com.mall.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   运费模板表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_freight_template
 */
public class PmsFreightTemplate implements Serializable {
    private Long id;

    private String name;

    private Boolean chargeType;

    private BigDecimal firstWeight;

    private BigDecimal firstFee;

    private BigDecimal continueWeight;

    private BigDecimal continueFee;

    private String dest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_freight_template
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_freight_template.id
     *
     * @return the value of pms_freight_template.id
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_freight_template.id
     *
     * @param id the value for pms_freight_template.id
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_freight_template.name
     *
     * @return the value of pms_freight_template.name
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_freight_template.name
     *
     * @param name the value for pms_freight_template.name
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_freight_template.charge_type
     *
     * @return the value of pms_freight_template.charge_type
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public Boolean getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_freight_template.charge_type
     *
     * @param chargeType the value for pms_freight_template.charge_type
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public void setChargeType(Boolean chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_freight_template.first_weight
     *
     * @return the value of pms_freight_template.first_weight
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public BigDecimal getFirstWeight() {
        return firstWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_freight_template.first_weight
     *
     * @param firstWeight the value for pms_freight_template.first_weight
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public void setFirstWeight(BigDecimal firstWeight) {
        this.firstWeight = firstWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_freight_template.first_fee
     *
     * @return the value of pms_freight_template.first_fee
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public BigDecimal getFirstFee() {
        return firstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_freight_template.first_fee
     *
     * @param firstFee the value for pms_freight_template.first_fee
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public void setFirstFee(BigDecimal firstFee) {
        this.firstFee = firstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_freight_template.continue_weight
     *
     * @return the value of pms_freight_template.continue_weight
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public BigDecimal getContinueWeight() {
        return continueWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_freight_template.continue_weight
     *
     * @param continueWeight the value for pms_freight_template.continue_weight
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public void setContinueWeight(BigDecimal continueWeight) {
        this.continueWeight = continueWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_freight_template.continue_fee
     *
     * @return the value of pms_freight_template.continue_fee
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public BigDecimal getContinueFee() {
        return continueFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_freight_template.continue_fee
     *
     * @param continueFee the value for pms_freight_template.continue_fee
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public void setContinueFee(BigDecimal continueFee) {
        this.continueFee = continueFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_freight_template.dest
     *
     * @return the value of pms_freight_template.dest
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public String getDest() {
        return dest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_freight_template.dest
     *
     * @param dest the value for pms_freight_template.dest
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    public void setDest(String dest) {
        this.dest = dest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_freight_template
     *
     * @mbg.generated Tue Jun 17 15:15:35 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", chargeType=").append(chargeType);
        sb.append(", firstWeight=").append(firstWeight);
        sb.append(", firstFee=").append(firstFee);
        sb.append(", continueWeight=").append(continueWeight);
        sb.append(", continueFee=").append(continueFee);
        sb.append(", dest=").append(dest);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}