package com.mall.mbg.model;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   商品-相册多对多关联表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_product_album_relation
 */
public class PmsProductAlbumRelation implements Serializable {
    private Long id;

    private Long productId;

    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_album_relation.id
     *
     * @return the value of pms_product_album_relation.id
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_album_relation.id
     *
     * @param id the value for pms_product_album_relation.id
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_album_relation.product_id
     *
     * @return the value of pms_product_album_relation.product_id
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_album_relation.product_id
     *
     * @param productId the value for pms_product_album_relation.product_id
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_album_relation.album_id
     *
     * @return the value of pms_product_album_relation.album_id
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_album_relation.album_id
     *
     * @param albumId the value for pms_product_album_relation.album_id
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_album_relation
     *
     * @mbg.generated Mon Jun 16 11:00:40 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", albumId=").append(albumId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}