package com.mall.mbg.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   秒杀活动主表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_flash_promotion
 */
public class SmsFlashPromotion implements Serializable {
    private Long id;

    private String title;

    private String subTitle;

    private String coverUrl;

    private String mobileCoverUrl;

    private Byte type;

    private Date startDate;

    private Date endDate;

    private Byte status;

    private Date createTime;

    private Date updateTime;

    private String description;

    private String styleConfig;

    private String customHtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_flash_promotion
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.id
     *
     * @return the value of sms_flash_promotion.id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.id
     *
     * @param id the value for sms_flash_promotion.id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.title
     *
     * @return the value of sms_flash_promotion.title
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.title
     *
     * @param title the value for sms_flash_promotion.title
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.sub_title
     *
     * @return the value of sms_flash_promotion.sub_title
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.sub_title
     *
     * @param subTitle the value for sms_flash_promotion.sub_title
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.cover_url
     *
     * @return the value of sms_flash_promotion.cover_url
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.cover_url
     *
     * @param coverUrl the value for sms_flash_promotion.cover_url
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.mobile_cover_url
     *
     * @return the value of sms_flash_promotion.mobile_cover_url
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getMobileCoverUrl() {
        return mobileCoverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.mobile_cover_url
     *
     * @param mobileCoverUrl the value for sms_flash_promotion.mobile_cover_url
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setMobileCoverUrl(String mobileCoverUrl) {
        this.mobileCoverUrl = mobileCoverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.type
     *
     * @return the value of sms_flash_promotion.type
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.type
     *
     * @param type the value for sms_flash_promotion.type
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.start_date
     *
     * @return the value of sms_flash_promotion.start_date
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.start_date
     *
     * @param startDate the value for sms_flash_promotion.start_date
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.end_date
     *
     * @return the value of sms_flash_promotion.end_date
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.end_date
     *
     * @param endDate the value for sms_flash_promotion.end_date
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.status
     *
     * @return the value of sms_flash_promotion.status
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.status
     *
     * @param status the value for sms_flash_promotion.status
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.create_time
     *
     * @return the value of sms_flash_promotion.create_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.create_time
     *
     * @param createTime the value for sms_flash_promotion.create_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.update_time
     *
     * @return the value of sms_flash_promotion.update_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.update_time
     *
     * @param updateTime the value for sms_flash_promotion.update_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.description
     *
     * @return the value of sms_flash_promotion.description
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.description
     *
     * @param description the value for sms_flash_promotion.description
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.style_config
     *
     * @return the value of sms_flash_promotion.style_config
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getStyleConfig() {
        return styleConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.style_config
     *
     * @param styleConfig the value for sms_flash_promotion.style_config
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setStyleConfig(String styleConfig) {
        this.styleConfig = styleConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion.custom_html
     *
     * @return the value of sms_flash_promotion.custom_html
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getCustomHtml() {
        return customHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion.custom_html
     *
     * @param customHtml the value for sms_flash_promotion.custom_html
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setCustomHtml(String customHtml) {
        this.customHtml = customHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", subTitle=").append(subTitle);
        sb.append(", coverUrl=").append(coverUrl);
        sb.append(", mobileCoverUrl=").append(mobileCoverUrl);
        sb.append(", type=").append(type);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", description=").append(description);
        sb.append(", styleConfig=").append(styleConfig);
        sb.append(", customHtml=").append(customHtml);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}