package com.mall.mbg.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   秒杀用户行为表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_flash_behavior
 */
public class SmsFlashBehavior implements Serializable {
    private Long id;

    private Long memberId;

    private Long productId;

    private Long promotionId;

    private Long sessionId;

    private Date subscribeTime;

    private Date buyTime;

    private String deviceInfo;

    private String ipAddress;

    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.id
     *
     * @return the value of sms_flash_behavior.id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.id
     *
     * @param id the value for sms_flash_behavior.id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.member_id
     *
     * @return the value of sms_flash_behavior.member_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.member_id
     *
     * @param memberId the value for sms_flash_behavior.member_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.product_id
     *
     * @return the value of sms_flash_behavior.product_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.product_id
     *
     * @param productId the value for sms_flash_behavior.product_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.promotion_id
     *
     * @return the value of sms_flash_behavior.promotion_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Long getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.promotion_id
     *
     * @param promotionId the value for sms_flash_behavior.promotion_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.session_id
     *
     * @return the value of sms_flash_behavior.session_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.session_id
     *
     * @param sessionId the value for sms_flash_behavior.session_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.subscribe_time
     *
     * @return the value of sms_flash_behavior.subscribe_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Date getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.subscribe_time
     *
     * @param subscribeTime the value for sms_flash_behavior.subscribe_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.buy_time
     *
     * @return the value of sms_flash_behavior.buy_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.buy_time
     *
     * @param buyTime the value for sms_flash_behavior.buy_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.device_info
     *
     * @return the value of sms_flash_behavior.device_info
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public String getDeviceInfo() {
        return deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.device_info
     *
     * @param deviceInfo the value for sms_flash_behavior.device_info
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setDeviceInfo(String deviceInfo) {
        this.deviceInfo = deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.ip_address
     *
     * @return the value of sms_flash_behavior.ip_address
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.ip_address
     *
     * @param ipAddress the value for sms_flash_behavior.ip_address
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_behavior.create_time
     *
     * @return the value of sms_flash_behavior.create_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_behavior.create_time
     *
     * @param createTime the value for sms_flash_behavior.create_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_behavior
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", productId=").append(productId);
        sb.append(", promotionId=").append(promotionId);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", subscribeTime=").append(subscribeTime);
        sb.append(", buyTime=").append(buyTime);
        sb.append(", deviceInfo=").append(deviceInfo);
        sb.append(", ipAddress=").append(ipAddress);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}