package com.mall.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   秒杀SKU关联表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_flash_sku_relation
 */
public class SmsFlashSkuRelation implements Serializable {
    private Long id;

    private Long productRelationId;

    private Long productId;

    private Long skuId;

    private String skuCode;

    private BigDecimal flashPrice;

    private Integer flashStock;

    private Integer flashLimit;

    private BigDecimal originalPrice;

    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_flash_sku_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.id
     *
     * @return the value of sms_flash_sku_relation.id
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.id
     *
     * @param id the value for sms_flash_sku_relation.id
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.product_relation_id
     *
     * @return the value of sms_flash_sku_relation.product_relation_id
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public Long getProductRelationId() {
        return productRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.product_relation_id
     *
     * @param productRelationId the value for sms_flash_sku_relation.product_relation_id
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setProductRelationId(Long productRelationId) {
        this.productRelationId = productRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.product_id
     *
     * @return the value of sms_flash_sku_relation.product_id
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.product_id
     *
     * @param productId the value for sms_flash_sku_relation.product_id
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.sku_id
     *
     * @return the value of sms_flash_sku_relation.sku_id
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.sku_id
     *
     * @param skuId the value for sms_flash_sku_relation.sku_id
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.sku_code
     *
     * @return the value of sms_flash_sku_relation.sku_code
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.sku_code
     *
     * @param skuCode the value for sms_flash_sku_relation.sku_code
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.flash_price
     *
     * @return the value of sms_flash_sku_relation.flash_price
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public BigDecimal getFlashPrice() {
        return flashPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.flash_price
     *
     * @param flashPrice the value for sms_flash_sku_relation.flash_price
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setFlashPrice(BigDecimal flashPrice) {
        this.flashPrice = flashPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.flash_stock
     *
     * @return the value of sms_flash_sku_relation.flash_stock
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public Integer getFlashStock() {
        return flashStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.flash_stock
     *
     * @param flashStock the value for sms_flash_sku_relation.flash_stock
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setFlashStock(Integer flashStock) {
        this.flashStock = flashStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.flash_limit
     *
     * @return the value of sms_flash_sku_relation.flash_limit
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public Integer getFlashLimit() {
        return flashLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.flash_limit
     *
     * @param flashLimit the value for sms_flash_sku_relation.flash_limit
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setFlashLimit(Integer flashLimit) {
        this.flashLimit = flashLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.original_price
     *
     * @return the value of sms_flash_sku_relation.original_price
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.original_price
     *
     * @param originalPrice the value for sms_flash_sku_relation.original_price
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_sku_relation.create_time
     *
     * @return the value of sms_flash_sku_relation.create_time
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_sku_relation.create_time
     *
     * @param createTime the value for sms_flash_sku_relation.create_time
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_sku_relation
     *
     * @mbg.generated Fri Jun 20 19:26:26 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productRelationId=").append(productRelationId);
        sb.append(", productId=").append(productId);
        sb.append(", skuId=").append(skuId);
        sb.append(", skuCode=").append(skuCode);
        sb.append(", flashPrice=").append(flashPrice);
        sb.append(", flashStock=").append(flashStock);
        sb.append(", flashLimit=").append(flashLimit);
        sb.append(", originalPrice=").append(originalPrice);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}