package com.mall.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   秒杀商品关联表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_flash_product_relation
 */
public class SmsFlashProductRelation implements Serializable {
    private Long id;

    private Long promotionId;

    private Long sessionId;

    private Long productId;

    private Boolean isSku;

    private BigDecimal flashPrice;

    private Integer flashStock;

    private Integer flashLimit;

    private BigDecimal originalPrice;

    private Integer sort;

    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_flash_product_relation
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.id
     *
     * @return the value of sms_flash_product_relation.id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.id
     *
     * @param id the value for sms_flash_product_relation.id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.promotion_id
     *
     * @return the value of sms_flash_product_relation.promotion_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.promotion_id
     *
     * @param promotionId the value for sms_flash_product_relation.promotion_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.session_id
     *
     * @return the value of sms_flash_product_relation.session_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.session_id
     *
     * @param sessionId the value for sms_flash_product_relation.session_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.product_id
     *
     * @return the value of sms_flash_product_relation.product_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.product_id
     *
     * @param productId the value for sms_flash_product_relation.product_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.is_sku
     *
     * @return the value of sms_flash_product_relation.is_sku
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Boolean getIsSku() {
        return isSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.is_sku
     *
     * @param isSku the value for sms_flash_product_relation.is_sku
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setIsSku(Boolean isSku) {
        this.isSku = isSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.flash_price
     *
     * @return the value of sms_flash_product_relation.flash_price
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public BigDecimal getFlashPrice() {
        return flashPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.flash_price
     *
     * @param flashPrice the value for sms_flash_product_relation.flash_price
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setFlashPrice(BigDecimal flashPrice) {
        this.flashPrice = flashPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.flash_stock
     *
     * @return the value of sms_flash_product_relation.flash_stock
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Integer getFlashStock() {
        return flashStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.flash_stock
     *
     * @param flashStock the value for sms_flash_product_relation.flash_stock
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setFlashStock(Integer flashStock) {
        this.flashStock = flashStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.flash_limit
     *
     * @return the value of sms_flash_product_relation.flash_limit
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Integer getFlashLimit() {
        return flashLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.flash_limit
     *
     * @param flashLimit the value for sms_flash_product_relation.flash_limit
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setFlashLimit(Integer flashLimit) {
        this.flashLimit = flashLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.original_price
     *
     * @return the value of sms_flash_product_relation.original_price
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.original_price
     *
     * @param originalPrice the value for sms_flash_product_relation.original_price
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.sort
     *
     * @return the value of sms_flash_product_relation.sort
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.sort
     *
     * @param sort the value for sms_flash_product_relation.sort
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_product_relation.create_time
     *
     * @return the value of sms_flash_product_relation.create_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_product_relation.create_time
     *
     * @param createTime the value for sms_flash_product_relation.create_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_product_relation
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", promotionId=").append(promotionId);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", productId=").append(productId);
        sb.append(", isSku=").append(isSku);
        sb.append(", flashPrice=").append(flashPrice);
        sb.append(", flashStock=").append(flashStock);
        sb.append(", flashLimit=").append(flashLimit);
        sb.append(", originalPrice=").append(originalPrice);
        sb.append(", sort=").append(sort);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}