package com.mall.mbg.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   秒杀场次表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_flash_session
 */
public class SmsFlashSession implements Serializable {
    private Long id;

    private Long promotionId;

    private String name;

    private String coverUrl;

    private Date startTime;

    private Date endTime;

    private Boolean repeatType;

    private Boolean status;

    private Date createTime;

    private String styleConfig;

    private String rulesConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_flash_session
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.id
     *
     * @return the value of sms_flash_session.id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.id
     *
     * @param id the value for sms_flash_session.id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.promotion_id
     *
     * @return the value of sms_flash_session.promotion_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Long getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.promotion_id
     *
     * @param promotionId the value for sms_flash_session.promotion_id
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.name
     *
     * @return the value of sms_flash_session.name
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.name
     *
     * @param name the value for sms_flash_session.name
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.cover_url
     *
     * @return the value of sms_flash_session.cover_url
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.cover_url
     *
     * @param coverUrl the value for sms_flash_session.cover_url
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.start_time
     *
     * @return the value of sms_flash_session.start_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.start_time
     *
     * @param startTime the value for sms_flash_session.start_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.end_time
     *
     * @return the value of sms_flash_session.end_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.end_time
     *
     * @param endTime the value for sms_flash_session.end_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.repeat_type
     *
     * @return the value of sms_flash_session.repeat_type
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Boolean getRepeatType() {
        return repeatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.repeat_type
     *
     * @param repeatType the value for sms_flash_session.repeat_type
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setRepeatType(Boolean repeatType) {
        this.repeatType = repeatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.status
     *
     * @return the value of sms_flash_session.status
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.status
     *
     * @param status the value for sms_flash_session.status
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.create_time
     *
     * @return the value of sms_flash_session.create_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.create_time
     *
     * @param createTime the value for sms_flash_session.create_time
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.style_config
     *
     * @return the value of sms_flash_session.style_config
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public String getStyleConfig() {
        return styleConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.style_config
     *
     * @param styleConfig the value for sms_flash_session.style_config
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setStyleConfig(String styleConfig) {
        this.styleConfig = styleConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session.rules_config
     *
     * @return the value of sms_flash_session.rules_config
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public String getRulesConfig() {
        return rulesConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session.rules_config
     *
     * @param rulesConfig the value for sms_flash_session.rules_config
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    public void setRulesConfig(String rulesConfig) {
        this.rulesConfig = rulesConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_session
     *
     * @mbg.generated Sat Jun 21 22:59:37 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", promotionId=").append(promotionId);
        sb.append(", name=").append(name);
        sb.append(", coverUrl=").append(coverUrl);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", repeatType=").append(repeatType);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", styleConfig=").append(styleConfig);
        sb.append(", rulesConfig=").append(rulesConfig);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}