package com.mall.mbg.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   用户场次订阅表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_flash_session_subscribe
 */
public class SmsFlashSessionSubscribe implements Serializable {
    private Long id;

    private Long memberId;

    private Long sessionId;

    private String content;

    private Byte status;

    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_flash_session_subscribe
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session_subscribe.id
     *
     * @return the value of sms_flash_session_subscribe.id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session_subscribe.id
     *
     * @param id the value for sms_flash_session_subscribe.id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session_subscribe.member_id
     *
     * @return the value of sms_flash_session_subscribe.member_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session_subscribe.member_id
     *
     * @param memberId the value for sms_flash_session_subscribe.member_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session_subscribe.session_id
     *
     * @return the value of sms_flash_session_subscribe.session_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session_subscribe.session_id
     *
     * @param sessionId the value for sms_flash_session_subscribe.session_id
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session_subscribe.content
     *
     * @return the value of sms_flash_session_subscribe.content
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session_subscribe.content
     *
     * @param content the value for sms_flash_session_subscribe.content
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session_subscribe.status
     *
     * @return the value of sms_flash_session_subscribe.status
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session_subscribe.status
     *
     * @param status the value for sms_flash_session_subscribe.status
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_session_subscribe.create_time
     *
     * @return the value of sms_flash_session_subscribe.create_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_session_subscribe.create_time
     *
     * @param createTime the value for sms_flash_session_subscribe.create_time
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_session_subscribe
     *
     * @mbg.generated Thu Jun 19 14:42:17 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", content=").append(content);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}