package com.mall.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   会员统计信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_member_statistics_info
 */
public class UmsMemberStatisticsInfo implements Serializable {
    private Long id;

    private Long memberId;

    private BigDecimal consumeAmount;

    private Integer orderCount;

    private Integer couponCount;

    private Integer commentCount;

    private Integer returnOrderCount;

    private Integer loginCount;

    private Integer attendCount;

    private Integer fansCount;

    private Integer collectProductCount;

    private Integer collectSubjectCount;

    private Integer collectTopicCount;

    private Integer collectCommentCount;

    private Integer inviteFriendCount;

    private Date recentOrderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.id
     *
     * @return the value of ums_member_statistics_info.id
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.id
     *
     * @param id the value for ums_member_statistics_info.id
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.member_id
     *
     * @return the value of ums_member_statistics_info.member_id
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.member_id
     *
     * @param memberId the value for ums_member_statistics_info.member_id
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.consume_amount
     *
     * @return the value of ums_member_statistics_info.consume_amount
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public BigDecimal getConsumeAmount() {
        return consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.consume_amount
     *
     * @param consumeAmount the value for ums_member_statistics_info.consume_amount
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setConsumeAmount(BigDecimal consumeAmount) {
        this.consumeAmount = consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.order_count
     *
     * @return the value of ums_member_statistics_info.order_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getOrderCount() {
        return orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.order_count
     *
     * @param orderCount the value for ums_member_statistics_info.order_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setOrderCount(Integer orderCount) {
        this.orderCount = orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.coupon_count
     *
     * @return the value of ums_member_statistics_info.coupon_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getCouponCount() {
        return couponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.coupon_count
     *
     * @param couponCount the value for ums_member_statistics_info.coupon_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setCouponCount(Integer couponCount) {
        this.couponCount = couponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.comment_count
     *
     * @return the value of ums_member_statistics_info.comment_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.comment_count
     *
     * @param commentCount the value for ums_member_statistics_info.comment_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.return_order_count
     *
     * @return the value of ums_member_statistics_info.return_order_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getReturnOrderCount() {
        return returnOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.return_order_count
     *
     * @param returnOrderCount the value for ums_member_statistics_info.return_order_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setReturnOrderCount(Integer returnOrderCount) {
        this.returnOrderCount = returnOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.login_count
     *
     * @return the value of ums_member_statistics_info.login_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.login_count
     *
     * @param loginCount the value for ums_member_statistics_info.login_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.attend_count
     *
     * @return the value of ums_member_statistics_info.attend_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getAttendCount() {
        return attendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.attend_count
     *
     * @param attendCount the value for ums_member_statistics_info.attend_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setAttendCount(Integer attendCount) {
        this.attendCount = attendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.fans_count
     *
     * @return the value of ums_member_statistics_info.fans_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getFansCount() {
        return fansCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.fans_count
     *
     * @param fansCount the value for ums_member_statistics_info.fans_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setFansCount(Integer fansCount) {
        this.fansCount = fansCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.collect_product_count
     *
     * @return the value of ums_member_statistics_info.collect_product_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getCollectProductCount() {
        return collectProductCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.collect_product_count
     *
     * @param collectProductCount the value for ums_member_statistics_info.collect_product_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setCollectProductCount(Integer collectProductCount) {
        this.collectProductCount = collectProductCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.collect_subject_count
     *
     * @return the value of ums_member_statistics_info.collect_subject_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getCollectSubjectCount() {
        return collectSubjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.collect_subject_count
     *
     * @param collectSubjectCount the value for ums_member_statistics_info.collect_subject_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setCollectSubjectCount(Integer collectSubjectCount) {
        this.collectSubjectCount = collectSubjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.collect_topic_count
     *
     * @return the value of ums_member_statistics_info.collect_topic_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getCollectTopicCount() {
        return collectTopicCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.collect_topic_count
     *
     * @param collectTopicCount the value for ums_member_statistics_info.collect_topic_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setCollectTopicCount(Integer collectTopicCount) {
        this.collectTopicCount = collectTopicCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.collect_comment_count
     *
     * @return the value of ums_member_statistics_info.collect_comment_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getCollectCommentCount() {
        return collectCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.collect_comment_count
     *
     * @param collectCommentCount the value for ums_member_statistics_info.collect_comment_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setCollectCommentCount(Integer collectCommentCount) {
        this.collectCommentCount = collectCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.invite_friend_count
     *
     * @return the value of ums_member_statistics_info.invite_friend_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Integer getInviteFriendCount() {
        return inviteFriendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.invite_friend_count
     *
     * @param inviteFriendCount the value for ums_member_statistics_info.invite_friend_count
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setInviteFriendCount(Integer inviteFriendCount) {
        this.inviteFriendCount = inviteFriendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_statistics_info.recent_order_time
     *
     * @return the value of ums_member_statistics_info.recent_order_time
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public Date getRecentOrderTime() {
        return recentOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_statistics_info.recent_order_time
     *
     * @param recentOrderTime the value for ums_member_statistics_info.recent_order_time
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    public void setRecentOrderTime(Date recentOrderTime) {
        this.recentOrderTime = recentOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated Sat Jun 21 00:04:23 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", consumeAmount=").append(consumeAmount);
        sb.append(", orderCount=").append(orderCount);
        sb.append(", couponCount=").append(couponCount);
        sb.append(", commentCount=").append(commentCount);
        sb.append(", returnOrderCount=").append(returnOrderCount);
        sb.append(", loginCount=").append(loginCount);
        sb.append(", attendCount=").append(attendCount);
        sb.append(", fansCount=").append(fansCount);
        sb.append(", collectProductCount=").append(collectProductCount);
        sb.append(", collectSubjectCount=").append(collectSubjectCount);
        sb.append(", collectTopicCount=").append(collectTopicCount);
        sb.append(", collectCommentCount=").append(collectCommentCount);
        sb.append(", inviteFriendCount=").append(inviteFriendCount);
        sb.append(", recentOrderTime=").append(recentOrderTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}